use_frameworks!

platform :ios, '9.0'

target 'MKLoRaWAN-PIR_Example' do
  pod 'MKLoRaWAN-PIR', :path => '../'

  target 'MKLoRaWAN-PIR_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
